name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'oracle'
        cache: 'maven'

    - name: Run Baloot 1 tests
      run: cd Baloot1 && mvn test -B -f pom.xml

    - name: Run Baloot 2 tests
      run: cd Baloot2 && mvn test -B -f pom.xml
