name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'oracle'

    - name: Go to Baloot1 directory
      run: pushd Baloot1

    - name: Run Baloot 1 tests
      run: mvn test -f pom.xml

    - name: Go to Baloot2 directory
      run: popd && pushd Baloot2

    - name: Run Baloot 2 tests
      run: mvn test -f Baloot2/pom.xml
